vizient:
  auth:
    idm:
      serviceUrl: http://nowhere/idmService
spring:
  datasource:
    url:  jdbc:sqlserver://localhost:1433;databaseName=CDBSLA_Metadata_Test
    password: Steal13Kittens@
    username: ziggy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: default
mart:
  datasource:
    url: jdbc:vertica://localhost:5433/docker?searchPath=public
    password: docker
    username: dbadmin
    driver-class-name: com.vertica.jdbc.Driver
