spring:
  datasource:
    url:  jdbc:sqlserver://host.pcfdev.io:1433;databaseName=CDBSLA_Metadata_Test
    password: 1mmaFakePassword@
    username: ziggy-test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: default
mart:
  datasource:
    url: jdbc:vertica://host.pcfdev.io:5433/docker?searchPath=public
    password: docker
    username: dbadmin
    driver-class-name: com.vertica.jdbc.Driver
wiremock:
  host: http://cdbslawiremock-integration.local.pcfdev.io
vizient:
  auth:
    sso:
      bridge:
        url:
          login: ${wiremock.host}/ssobridge
